C> @file
C>
C> Perform a simple gradient spherical transform
C> @author IREDELL @date 96-02-29
C>
C> THIS SUBPROGRAM PERFORMS A SPHERICAL TRANSFORM
C> BETWEEN SPECTRAL COEFFICIENTS OF A SCALAR FIELD
C> AND ITS MEAN AND GRADIENT ON A GLOBAL CYLINDRICAL GRID.
C> THE WAVE-SPACE CAN BE EITHER TRIANGULAR OR RHOMBOIDAL.
C> THE GRID-SPACE CAN BE EITHER AN EQUALLY-SPACED GRID
C> (WITH OR WITHOUT POLE POINTS) OR A GAUSSIAN GRID.
C> THE WAVE FIELD IS IN SEQUENTIAL 'IBM ORDER'.
C> THE GRID FIELS IS INDEXED EAST TO WEST, THEN NORTH TO SOUTH.
C> FOR MORE FLEXIBILITY AND EFFICIENCY, CALL SPTRAN.
C> SUBPROGRAM CAN BE CALLED FROM A MULTIPROCESSING ENVIRONMENT.
C>
C> @param IROMB    - INTEGER SPECTRAL DOMAIN SHAPE
C>                (0 FOR TRIANGULAR, 1 FOR RHOMBOIDAL)
C> @param MAXWV    - INTEGER SPECTRAL TRUNCATION
C> @param IDRT     - INTEGER GRID IDENTIFIER
C>                (IDRT=4 FOR GAUSSIAN GRID,
C>                 IDRT=0 FOR EQUALLY-SPACED GRID INCLUDING POLES,
C>                 IDRT=256 FOR EQUALLY-SPACED GRID EXCLUDING POLES)
C> @param IMAX     - INTEGER EVEN NUMBER OF LONGITUDES.
C> @param JMAX     - INTEGER NUMBER OF LATITUDES.
C> @param WAVE     - REAL (*) WAVE FIELD IF IDIR>0
C> @param GRIDMN   - REAL GLOBAL MEAN IF IDIR<0
C> @param GRIDX    - REAL (IMAX,JMAX) GRID X-GRADIENTS (E->W,N->S) IF IDIR<0
C> @param GRIDY    - REAL (IMAX,JMAX) GRID Y-GRADIENTS (E->W,N->S) IF IDIR<0
C> @param IDIR     - INTEGER TRANSFORM FLAG
C>                (IDIR>0 FOR WAVE TO GRID, IDIR<0 FOR GRID TO WAVE)
C> @param WAVE     - REAL (*) WAVE FIELD IF IDIR<0
C> @param GRIDMN   - REAL GLOBAL MEAN IF IDIR>0
C> @param GRIDX    - REAL (IMAX,JMAX) GRID X-GRADIENTS (E->W,N->S) IF IDIR>0
C> @param GRIDY    - REAL (IMAX,JMAX) GRID Y-GRADIENTS (E->W,N->S) IF IDIR>0
C>
C> SUBPROGRAMS CALLED:
C>  - SPTRAND      PERFORM A GRADIENT SPHERICAL TRANSFORM
C>  - NCPUS        GETS ENVIRONMENT NUMBER OF CPUS
C>
C> REMARKS: MINIMUM GRID DIMENSIONS FOR UNALIASED TRANSFORMS TO SPECTRAL:
C>   DIMENSION                    |LINEAR              |QUADRATIC
C>   -----------------------      |---------           |-------------
C>   IMAX                         |2*MAXWV+2           |3*MAXWV/2*2+2
C>   JMAX (IDRT=4,IROMB=0)        |1*MAXWV+1           |3*MAXWV/2+1
C>   JMAX (IDRT=4,IROMB=1)        |2*MAXWV+1           |5*MAXWV/2+1
C>   JMAX (IDRT=0,IROMB=0)        |2*MAXWV+3           |3*MAXWV/2*2+3
C>   JMAX (IDRT=0,IROMB=1)        |4*MAXWV+3           |5*MAXWV/2*2+3
C>   JMAX (IDRT=256,IROMB=0)      |2*MAXWV+1           |3*MAXWV/2*2+1
C>   JMAX (IDRT=256,IROMB=1)      |4*MAXWV+1           |5*MAXWV/2*2+1
      SUBROUTINE SPTEZD(IROMB,MAXWV,IDRT,IMAX,JMAX,
     &                  WAVE,GRIDMN,GRIDX,GRIDY,IDIR)

      REAL WAVE(*),GRIDX(IMAX,JMAX),GRIDY(IMAX,JMAX)
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      JC=NCPUS()
      CALL SPTRAND(IROMB,MAXWV,IDRT,IMAX,JMAX,1,
     &             0,0,0,0,0,0,0,0,JC,
     &             WAVE,GRIDMN,
     &             GRIDX,GRIDX(1,JMAX),GRIDY,GRIDY(1,JMAX),1)
C - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
      END
