
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-pfunit
          uses: actions/checkout@v2
          with:
            repository: Goddard-Fortran-Ecosystem/pFUnit
            path: pfunit
