# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout pfunit
        uses: actions/checkout@v2
          with:
            repository: Goddard-Fortran-Ecosystem/pFUnit
            path: pfunit
